INSERT INTO demo_events
/*+ OPTIONS('properties.transaction.timeout.ms'='300000') */
VALUES
  ('evt-1',  10, CAST(CURRENT_TIMESTAMP AS TIMESTAMP(3)) - INTERVAL '90' SECOND, 'A'),
  ('evt-2',  20, CAST(CURRENT_TIMESTAMP AS TIMESTAMP(3)) - INTERVAL '80' SECOND, 'B'),
  ('evt-3',   5, CAST(CURRENT_TIMESTAMP AS TIMESTAMP(3)) - INTERVAL '70' SECOND, 'A'),
  ('evt-4',  30, CAST(CURRENT_TIMESTAMP AS TIMESTAMP(3)) - INTERVAL '60' SECOND, 'A'),
  ('evt-5',  15, CAST(CURRENT_TIMESTAMP AS TIMESTAMP(3)) - INTERVAL '50' SECOND, 'B'),
  ('evt-6',  25, CAST(CURRENT_TIMESTAMP AS TIMESTAMP(3)) - INTERVAL '40' SECOND, 'A'),
  ('evt-7',  40, CAST(CURRENT_TIMESTAMP AS TIMESTAMP(3)) - INTERVAL '30' SECOND, 'B'),
  ('evt-8',  10, CAST(CURRENT_TIMESTAMP AS TIMESTAMP(3)) - INTERVAL '20' SECOND, 'A'),
  ('evt-9',  35, CAST(CURRENT_TIMESTAMP AS TIMESTAMP(3)) - INTERVAL '10' SECOND, 'A'),
  ('evt-10', 20, CAST(CURRENT_TIMESTAMP AS TIMESTAMP(3)) - INTERVAL '5'  SECOND, 'B');
